### ISSUE TITLE
Python 3.11 bug

### ISSUE THREAD

**Issue by RaZer0r** [jnimmo/hass-smartvideohub#2]
I get an error on loading:
`
2023-11-14 21:20:19.223 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up smartvideohub platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 320, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/smartvideohub/media_player.py", line 54, in async_setup_platform
    from .pyvideohub import SmartVideoHub
  File "/config/custom_components/smartvideohub/pyvideohub.py", line 12, in <module>
    class SmartVideoHub(asyncio.Protocol):
  File "/config/custom_components/smartvideohub/pyvideohub.py", line 174, in SmartVideoHub
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'
2023-11-14 21:20:21.711 ERROR (MainThread) [homeassistant.components.mqtt.client] Failed to connect to MQTT server due to exception: [Errno 111] Connection refused
2023-11-14 21:20:30.088 WARNING (MainThread) [homeassistant.config_entries] Config entry 'MR 2' for shelly integration not ready yet: DeviceConnectionError(); Retrying in background
2023-11-14 21:20:30.090 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Café 123' for shelly integration not ready yet: DeviceConnectionError(); Retrying in background
2023-11-14 21:20:53.742 WARNING (MainThread) [homeassistant.components.kodi.media_player] Unable to connect to Kodi via websocket
2023-11-14 21:21:11.700 ERROR (MainThread) [frontend.js.latest.202306080] https://hass.samvaerket.dk/config/integrations/dashboard:0:0 ResizeObserver loop completed with undelivered notifications.
`

which seems to do with python 3.11. Is there any chance this is an easy fix?

**Comment by rohanwright** [comment]
Im also interested in this integration if we can get it working again?

**Comment by jnimmo** [comment]
I've added a fork and tried to update to swap out the deprecated methods - give that a try - https://github.com/jnimmo/hass-smartvideohub/tree/python311patch (sorry I haven't had a chance to test it, so it may not help)

**Comment by RaZer0r** [comment]
i've fixed it with an update on the way asyncio is being called (my dear friend ChatGPT helped a lot xD)

**Comment by RaZer0r** [comment]
i also updated it to be able to use utf-8 characters, as some of our outputs contained æøå xD (welcome to scandinavian character sets xd)
