### ISSUE TITLE
Issue with running multiple simultaneous connections

### ISSUE THREAD

**Issue by rohanwright** [jnimmo/hass-smartvideohub#5]
We have two videohubs, I can get the integration to work with one, but if I try to add a second on I get a bunch of errors.

I'm defining the two devices like this:

```
  - platform: smartvideohub
    host: 192.168.10.106
    port: 9990
    name: VideohubA

  - platform: smartvideohub
    host: 192.168.10.107
    port: 9990
    name: VideohubB
```

These are the errors I'm receiving:

```
2023-11-30 14:50:29.382 ERROR (MainThread) [homeassistant] Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1003, in _read_ready__data_received
self._protocol.data_received(data)
File "/config/custom_components/smartvideohub/pyvideohub.py", line 76, in data_received
self.outputs[output_id]["input_name"] = self.inputs[input_id]
~~~~~~~~~~~^^^^^^^^^^
KeyError: 17
2023-11-30 14:50:29.384 ERROR (MainThread) [custom_components.smartvideohub.pyvideohub] Connection to the server lost
2023-11-30 14:50:31.368 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up smartvideohub platform for media_player
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/smartvideohub/media_player.py", line 69, in async_setup_platform
[
File "/config/custom_components/smartvideohub/media_player.py", line 70, in <listcomp>
SmartVideoHubOutput(
File "/config/custom_components/smartvideohub/media_player.py", line 104, in __init__
self._output_name = output["name"]
~~~~~~^^^^^^^^
KeyError: 'name'
```

**Comment by rohanwright** [comment]
Hi, I managed to figure this issue out, was an issue with the source IDs not being unique.
need to change line 110 in media_player.py to:
`self._attr_unique_id = f"smartvideohub_{entity_prefix}_output_{self._output_id}"`

**Comment by Cypris2010** [comment]
I have the 2025.6 Version running and have to create new devices with the web interface not by config code. I can't create a second video player.
